# default config path is ./
# use -config=<path> to choose a different one

[server]
#host = "localhost"
#port = 5000

[postgres]
#host = "localhost"
#port = 5432
#username = "postgres"
#password = "!qV)SQkBXF)X#iTA4)R9" #""
#database = "keepthemoment" #"postgres"

[redis]
#host = "localhost"
#port = 6379
#password = ""

[minio]
#host = "localhost"
#port = 9000
#access_key = "minioadmin"
#secret_key = "minioadmin"

[email]
#host = "localhost"
#port = 465
#email = "root@localhost"
#password = ""

[firebase]
#projectid = ""
#apikey = ""
